-- Migration 011: document the 9 columns added to generation_jobs without
-- a versioned migration during Sprint 0/1.
-- Sprint 2 issue #6.
--
-- These columns exist in prod but were not declared in any 00X_*.sql, so
-- a fresh `npx supabase db reset` (or any disaster-recovery rebuild from
-- migrations) would produce a schema that diverges from prod and causes
-- runtime to crash on first query.
--
-- All ADDs use IF NOT EXISTS so re-applying to prod is a no-op. The
-- intent is purely declarative — make the migrations folder the
-- authoritative source of truth again, and stop the bleeding before any
-- new runtime code piles on more undocumented columns.
--
-- Each column carries a COMMENT explaining its role + the pre-Sprint-2
-- runtime path that introduced it. Future readers don't have to spelunk
-- through commits to learn why each exists.

-- ── 1. pipeline_log ───────────────────────────────────────────────────
-- Append-only JSONB log of pipeline events: SHOT_TYPE, MODE_SELECTED,
-- PATTERN_COMPARED, GENERATION_START, PROVIDER_USED, VERIFICATION,
-- DELTA_E_*, RATE_LIMIT_*, COST_CAP_EXCEEDED, etc. Used by health-check,
-- regression-alert, retry-rate-limited, and the case-signature backfill.
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS pipeline_log JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN generation_jobs.pipeline_log IS
  'Append-only event log. Each entry: {ts, event, detail, data?}. Source of truth for cumulative per-attempt costs (cost-cap.ts) and historical decisions when generation_jobs columns get overwritten on retry.';

-- ── 2. claimed_by + claimed_at + worker_id ────────────────────────────
-- claim_next_job() RPC populates claimed_by + claimed_at with the
-- worker that won the FOR UPDATE SKIP LOCKED race. worker_id is an
-- older alias from the inngest era — kept NULL in current runtime,
-- not removed because pre-Sprint-2 jobs still reference it.
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS claimed_by TEXT;
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ;
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS worker_id TEXT;

COMMENT ON COLUMN generation_jobs.claimed_by IS
  'Worker id (region-uuid) that holds the current claim. Set by claim_next_job() RPC, cleared on terminal status. Used by stale-claim recovery in /api/cron/health-check.';
COMMENT ON COLUMN generation_jobs.claimed_at IS
  'When the current claim was acquired. Stale-claim threshold = updated_at older than CHAIN_STALE_THRESHOLD_MS (constants.ts).';
COMMENT ON COLUMN generation_jobs.worker_id IS
  'DEPRECATED — pre-claim_next_job era. New code uses claimed_by. Left in schema because legacy rows reference it.';

-- ── 3. trace_id + trigger_source ──────────────────────────────────────
-- Pre-Sprint-1 telemetry attempt — superseded by pipeline_log + the
-- model_id/provider_used/cost_usd_actual columns from migration 007.
-- Kept because old jobs reference them; new code does not write them.
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS trace_id TEXT;
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS trigger_source TEXT;

COMMENT ON COLUMN generation_jobs.trace_id IS
  'DEPRECATED — pre-Sprint-1 telemetry. NULL in current runtime. Use pipeline_log for tracing.';
COMMENT ON COLUMN generation_jobs.trigger_source IS
  'DEPRECATED — pre-Sprint-1. NULL in current runtime.';

-- ── 4. gemini_response_meta ───────────────────────────────────────────
-- Raw Gemini API metadata (token counts, finish reasons, safety ratings)
-- captured for debugging. Not aggregated anywhere.
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS gemini_response_meta JSONB;

COMMENT ON COLUMN generation_jobs.gemini_response_meta IS
  'Raw provider response metadata (token counts, finish reasons, safety ratings). Debug-only — not aggregated. Populated by lib/gemini/client.ts.';

-- ── 5. swatch_pattern_text ────────────────────────────────────────────
-- Text description of the swatch pattern, generated by lib/swatch-planner.ts
-- (gemini-2.0-flash analysis). Re-used across attempts of the same job to
-- avoid re-analyzing the swatch — analyzeSwatchPattern() writes here once
-- per swatch, then process-next reads it on retries.
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS swatch_pattern_text TEXT;

COMMENT ON COLUMN generation_jobs.swatch_pattern_text IS
  'Cached swatch-pattern analysis from lib/swatch-planner.ts (gemini-2.0-flash). Avoids re-analyzing on retries.';

-- ── 6. verification_raw ───────────────────────────────────────────────
-- Full verifier 2.5 Pro response when the swatch fidelity check ran.
-- Used to populate prompt_metadata.verification_score / pass / issues
-- and persisted for offline debugging of false positives/negatives.
ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS verification_raw JSONB;

COMMENT ON COLUMN generation_jobs.verification_raw IS
  'Raw response from gemini-2.5-pro verifier (lib/swatch-verifier.ts). Captured for offline debugging of verifier accuracy.';

-- ── 7. Index on (claimed_by, claimed_at) for stale-claim recovery ─────
-- The /api/cron/health-check stale-claim sweep filters
--   WHERE status = 'generating' AND updated_at < threshold
-- and looks at claimed_by to attribute the stuck worker. A composite
-- index on (status, updated_at) would already help, but at current
-- prod scale (3k jobs) the planner picks the right path without it.
-- Index left out intentionally — add when generation_jobs grows past
-- 100k rows AND the health-check query shows up in pg_stat_statements.

DO $$
BEGIN
  RAISE NOTICE '[011] documented 9 schema-drift columns (additive, no behavioral change)';
END $$;
